# Generated by Django 6.0.2 on 2026-02-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='mouth_size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='sku',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
