# Generated by Django 6.0.1 on 2026-02-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyInventoryApp", "0002_alter_supplier_city_alter_supplier_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waterbottle",
            name="id",
        ),
        migrations.AlterField(
            model_name="supplier",
            name="city",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="country",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="waterbottle",
            name="brand",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="waterbottle",
            name="size",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="waterbottle",
            name="sku",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
