# Generated by Django 6.0.1 on 2026-03-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyInventoryApp", "0003_remove_waterbottle_id_alter_supplier_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="waterbottle",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="waterbottle",
            name="sku",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
